=== Nodling/WWIDesigner/WWIDesigner/src/main/com/wwidesigner/geometry/bind/Instrument.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:wii="http://www.wwidesigner.com/Instrument" targetNamespace="http://www.wwidesigner.com/Instrument"
	elementFormDefault="unqualified">

	<xsd:element name="instrument" type="wii:Instrument" />

	<xsd:complexType name="Instrument">
		<xsd:annotation>
			<xsd:documentation>The physical geometry of a wood wind. Dimensions
				may represent initial values subject to optimization or final values
				fixed throughout the calculations.
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="name" type="xsd:string" />
			<xsd:element name="description" type="xsd:string"
				minOccurs="0" />
			<xsd:element name="lengthType" type="wii:LengthType">
				<xsd:annotation>
					<xsd:documentation>Units of measurement, applied to all dimensions.
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="mouthpiece" type="wii:Mouthpiece"
				minOccurs="0">
				<xsd:annotation>
					<xsd:documentation>Description of the "drive" end.
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="mouthpieceOrigin" type="wii:BorePoint">
				<xsd:annotation>
					<xsd:documentation>BorePoint that defines the flute origin. Center
						of embouchure hole, top of fipple window, etc.
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="borePoint" type="wii:BorePoint"
				maxOccurs="unbounded">
				<xsd:annotation>
					<xsd:documentation>Sequence of inside diameter measurements for
						non-uniform bore, from fipple, cork or other head-end termination,
						to bottom-end. Assume segments between bore points
						are conical, with linear increase in diameter.
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="hole" type="wii:Hole" minOccurs="0"
				maxOccurs="unbounded">
				<xsd:annotation>
					<xsd:documentation>Hole specifications for toneholes,
						from mouthpiece to bottom-end.
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="termination" type="wii:Termination">
				<xsd:annotation>
					<xsd:documentation>Description of bottom end. The position and bore
						diameter of the termination is specified by the borePoint with the
						greatest position.
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:simpleType name="LengthType">
		<xsd:annotation>
			<xsd:documentation>An enumeration, applied globally to all
				Dimensions, indicating mm or inch values.
			</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="xsd:token">
			<xsd:enumeration value="mm" />
			<xsd:enumeration value="in" />
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="Optimization">
		<xsd:annotation>
			<xsd:documentation>An enumeration, applied individually to all
				Dimension values, that is interpreted by the optimization engine. We
				might want to add other/additional values to this enumeration.
			</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="xsd:token">
			<xsd:enumeration value="FIXED" />
			<xsd:enumeration value="FREE" />
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:complexType name="Dimension">
		<xsd:annotation>
			<xsd:documentation>Base class for a double value and associated
				optimization flag.
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="value" type="xsd:double" />
			<xsd:element name="optimization" type="wii:Optimization" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="ZeroOrMore">
		<xsd:annotation>
			<xsd:documentation>A non-negative Dimension.</xsd:documentation>
		</xsd:annotation>
		<xsd:complexContent>
			<xsd:restriction base="wii:Dimension">
				<xsd:sequence>
					<xsd:element name="value">
						<xsd:simpleType>
							<xsd:restriction base="xsd:double">
								<xsd:minInclusive value="0" />
							</xsd:restriction>
						</xsd:simpleType>
					</xsd:element>
					<xsd:element name="optimization" type="wii:Optimization" />
				</xsd:sequence>
			</xsd:restriction>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:complexType name="MoreThanZero">
		<xsd:annotation>
			<xsd:documentation>A Dimension with a value greater than 0.
			</xsd:documentation>
		</xsd:annotation>
		<xsd:complexContent>
			<xsd:restriction base="wii:Dimension">
				<xsd:sequence>
					<xsd:element name="value">
						<xsd:simpleType>
							<xsd:restriction base="xsd:double">
								<xsd:minExclusive value="0" />
							</xsd:restriction>
						</xsd:simpleType>
					</xsd:element>
					<xsd:element name="optimization" type="wii:Optimization" />
				</xsd:sequence>
			</xsd:restriction>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:complexType name="BorePoint">
		<xsd:annotation>
			<xsd:documentation>Represents a bore position and effective diameter,
				measured from an arbitrary position, greater positions toward the
				foot of the instrument. Diameters between
				borePoints are linearly interpolated.
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="borePosition" type="wii:Dimension" />
			<xsd:element name="boreDiameter" type="wii:ZeroOrMore" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="Key">
		<xsd:annotation>
			<xsd:documentation>Representation of a key mechanism over a tone
				hole.
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="diameter" type="wii:MoreThanZero" />
			<xsd:element name="holeDiameter" type="wii:ZeroOrMore" />
			<xsd:element name="height" type="wii:ZeroOrMore" />
			<xsd:element name="thickness" type="wii:ZeroOrMore" />
			<xsd:element name="wallThickness" type="wii:ZeroOrMore" />
			<xsd:element name="chimneyHeight" type="wii:ZeroOrMore" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="Hole">
		<xsd:annotation>
			<xsd:documentation>A tone hole with optional key mechanism. The tone
				hole assumes a cylindrical shape with a radiused inner edge. More
				complexity is possible, including truncated conical profiles and
				angled holes.
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="name" type="xsd:string" minOccurs="0" />
			<xsd:element name="position" type="wii:ZeroOrMore">
				<xsd:annotation>
					<xsd:documentation>Position of hole, relative to reference
						position, measured from mouthpiece to bottom end.
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="diameter" type="wii:MoreThanZero" />
			<xsd:element name="height" type="wii:MoreThanZero" />
			<xsd:element name="innerCurvatureRadius" type="wii:ZeroOrMore"
				minOccurs="0" />
			<xsd:element name="key" type="wii:Key" minOccurs="0" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="Mouthpiece">
		<xsd:annotation>
			<xsd:documentation>First pass at a sound-mechanism model. Represents
				a choice between (1) a characteristic length, (2) a flute-type
				embouchure, and (3) a fipple mechanism. We need to add reeds,
				end-blown flutes, etc. The position of the mouthpiece is taken from
				the mouthpieceOrigin borePoint.
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:choice>
				<xsd:element name="characteristicLength" type="wii:MoreThanZero" />
				<xsd:element name="embouchureHole">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="innerDiameter" type="wii:MoreThanZero">
								<xsd:annotation>
									<xsd:documentation>Equivalent diameter of hole inside the tube.
									</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="outerDiameter" type="wii:MoreThanZero">
								<xsd:annotation>
									<xsd:documentation>Equivalent diameter of hole outside the
										tube.
									</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="height" type="wii:MoreThanZero">
								<xsd:annotation>
									<xsd:documentation>Chimney height of hole, from inside to
										outsides.
									</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="headPoint" type="wii:BorePoint"
								maxOccurs="unbounded">
								<xsd:annotation>
									<xsd:documentation>BorePoints that define the bore profile
										above the embouchure hole center. Each position is relative to
										the mouthpieceOrigin position, decreasing as you move up the
										flute. Because the origin is in the center of the embouchure
										hole, there must be at least one headPoint.
									</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="fipple">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="windowLength" type="wii:MoreThanZero">
								<xsd:annotation>
									<xsd:documentation>Distance from fipple to sound blade.
									</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="windowWidth" type="wii:MoreThanZero">
								<xsd:annotation>
									<xsd:documentation>Side-to-side width of window.
									</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="fippleFactor" type="wii:MoreThanZero" minOccurs="0">
								<xsd:annotation>
									<xsd:documentation>An empirical multiplier of the calculated
										characteristic dimension of the window.
										The impedance model does not use this value.
									</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="windowHeight" type="wii:MoreThanZero">
								<xsd:annotation>
									<xsd:documentation>Average "height" of window, between inside
										and outside of tube.
									</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="windwayLength" type="wii:MoreThanZero"
								minOccurs="0">
								<xsd:annotation>
									<xsd:documentation>Length of windway, from beak to exit.
									</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="windwayHeight" type="wii:MoreThanZero">
								<xsd:annotation>
									<xsd:documentation>Average height of windway at the exit.
									</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
			</xsd:choice>
			<xsd:element name="beta">
				<xsd:annotation>
					<xsd:documentation>Jet spatial amplification factor
						typically between 0.3 and 0.4.
						See Auvray, et al., "Regime change and oscillation
						thresholds in recorder-like instruments",
						J. Acoust. Soc. Am. 131 (2), February 2012
					</xsd:documentation>
				</xsd:annotation>
				<xsd:simpleType>
					<xsd:restriction base="xsd:double">
						<xsd:minExclusive value="0"></xsd:minExclusive>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="Termination">
		<xsd:annotation>
			<xsd:documentation>Description of the opening at the bottom end of
				the instrument.
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="flangeDiameter" type="wii:ZeroOrMore">
				<xsd:annotation>
					<xsd:documentation>Outer diameter of the open end.
						Zero if the bottom end is closed.
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>

</xsd:schema>

=== Nodling/WWIDesigner/WWIDesigner/src/main/com/wwidesigner/geometry/bind/example/fife.xml
<?xml version="1.0" encoding="utf-8"?>
<wii:instrument xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns:wii="http://www.wwidesigner.com/Instrument"
         xsi:schemaLocation="http://www.wwidesigner.com/Instrument ../Instrument.xsd ">
	<name>Bb Fife</name>
	<description>6-hole maple fife, cylindrical bore, Bb.
		Positions measured from far left-hand end, above the cork.
	</description>
	<lengthType>mm</lengthType>
	<mouthpiece>
		<embouchureHole>
			<innerDiameter>
				<value>9.6</value>
				<optimization>FIXED</optimization>
			</innerDiameter>
			<outerDiameter>
				<value>9.6</value>
				<optimization>FIXED</optimization>
			</outerDiameter>
			<height>
				<value>4.8</value>
				<optimization>FIXED</optimization>
			</height>
			<headPoint>
				<borePosition>
					<value>83.5</value>
					<optimization>FIXED</optimization>
				</borePosition>
				<boreDiameter>
					<value>12.4</value>
					<optimization>FIXED</optimization>
				</boreDiameter>
			</headPoint>
		</embouchureHole>
		
		<beta>0.4</beta>
	</mouthpiece>
	<mouthpieceOrigin>
		<borePosition><value>73.5</value><optimization>FIXED</optimization></borePosition>
		<boreDiameter><value>12.4</value><optimization>FIXED</optimization></boreDiameter>
	</mouthpieceOrigin>
	<borePoint>
		<borePosition><value>73.5</value><optimization>FIXED</optimization></borePosition>
		<boreDiameter><value>12.4</value><optimization>FIXED</optimization></boreDiameter>
	</borePoint>
	<borePoint>
		<borePosition><value>420.5</value><optimization>FIXED</optimization></borePosition>
		<boreDiameter><value>12.4</value><optimization>FIXED</optimization></boreDiameter>
	</borePoint>
	<hole>
		<position><value>234.0</value><optimization>FREE</optimization></position>
		<diameter><value>6.2</value><optimization>FREE</optimization></diameter>
		<height><value>4.2</value><optimization>FIXED</optimization></height>
	</hole>
	<hole>
		<position><value>257.0</value><optimization>FREE</optimization></position>
		<diameter><value>7.0</value><optimization>FREE</optimization></diameter>
		<height><value>4.1</value><optimization>FIXED</optimization></height>
	</hole>
	<hole>
		<position><value>281.0</value><optimization>FREE</optimization></position>
		<diameter><value>7.0</value><optimization>FREE</optimization></diameter>
		<height><value>3.9</value><optimization>FIXED</optimization></height>
	</hole>
	<hole>
		<position><value>314.0</value><optimization>FREE</optimization></position>
		<diameter><value>6.2</value><optimization>FREE</optimization></diameter>
		<height><value>3.6</value><optimization>FIXED</optimization></height>
	</hole>
	<hole>
		<position><value>335.5</value><optimization>FREE</optimization></position>
		<diameter><value>8.1</value><optimization>FREE</optimization></diameter>
		<height><value>3.3</value><optimization>FIXED</optimization></height>
	</hole>
	<hole>
		<position><value>360.5</value><optimization>FREE</optimization></position>
		<diameter><value>6.4</value><optimization>FREE</optimization></diameter>
		<height><value>3.0</value><optimization>FIXED</optimization></height>
	</hole>
	<termination>
		<flangeDiameter><value>17.5</value><optimization>FIXED</optimization></flangeDiameter>
	</termination>
</wii:instrument>

=== Nodling/WWIDesigner/WWIDesigner/src/test/com/wwidesigner/optimization/example/BP7.xml
<?xml version="1.0" encoding="utf-8"?>
<wii:instrument xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns:wii="http://www.wwidesigner.com/Instrument"
         xsi:schemaLocation="http://www.wwidesigner.com/Instrument ../Instrument.xsd ">
	<name>BP7 Whistle</name>
	<description>6-hole PVC whistle, high D, A=440 Just Intonation</description>
	<lengthType>mm</lengthType>
	<mouthpiece>
		<position>0.</position>
		<fipple>
			<windowLength>5.4</windowLength>
			<windowWidth>6.5</windowWidth>
			<windowHeight>2.1</windowHeight>
			<windwayLength>21.</windwayLength>
			<windwayHeight>1.6</windwayHeight>
		</fipple>
		<beta>0.4</beta>
	</mouthpiece>
	<borePoint>
		<borePosition>0</borePosition>
		<boreDiameter>10.05</boreDiameter>
	</borePoint>
	<borePoint>
		<borePosition>19.6</borePosition>
		<boreDiameter>11.9</boreDiameter>
	</borePoint>
	<borePoint>
		<borePosition>267.5</borePosition>
		<boreDiameter>11.9</boreDiameter>
	</borePoint>
	<hole>
		<borePosition>117.0</borePosition>
		<diameter>5.6</diameter>
		<height>1.9</height>
	</hole>
	<hole>
		<borePosition>139.5</borePosition>
		<diameter>6.0</diameter>
		<height>1.9</height>
	</hole>
	<hole>
		<borePosition>158.5</borePosition>
		<diameter>6.0</diameter>
		<height>1.9</height>
	</hole>
	<hole>
		<borePosition>186.5</borePosition>
		<diameter>6.0</diameter>
		<height>1.9</height>
	</hole>
	<hole>
		<borePosition>203.0</borePosition>
		<diameter>7.9</diameter>
		<height>1.9</height>
	</hole>
	<hole>
		<borePosition>227.5</borePosition>
		<diameter>7.5</diameter>
		<height>1.9</height>
	</hole>
	<termination>
		<flangeDiameter>15.9</flangeDiameter>
	</termination>
</wii:instrument>

=== Nodling/WWIDesigner/WWIDesigner/src/test/com/wwidesigner/optimization/example/LightG6HoleNAF.xml
<?xml version="1.0" encoding="UTF-8"?>
<wii:instrument xmlns:wii="http://www.wwidesigner.com/Instrument"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.wwidesigner.com/Instrument ../../../../../main/com/wwidesigner/geometry/bind/Instrument.xsd ">
	<name>Ken Light G, 6 hole NAF</name>
	<description>Ken Light straight bore NAF with 6 holes</description>
	<lengthType>mm</lengthType>
	<mouthpiece>
		<position>6.3</position>
		<fipple>
			<windowLength>6.3</windowLength>
			<windowWidth>9.54</windowWidth>
		 	<fippleFactor>0.843</fippleFactor>
			<windowHeight>7</windowHeight>
			<windwayHeight>0.8</windwayHeight>
		</fipple>
		<beta>0.4</beta>
	</mouthpiece>
	<borePoint>
		<borePosition>0</borePosition>
		<boreDiameter>21.62</boreDiameter>
	</borePoint>
	<borePoint>
		<borePosition>369.32</borePosition>
		<boreDiameter>21.62</boreDiameter>
	</borePoint>
	<hole>
		<borePosition>104.2</borePosition>
		<diameter>7.76</diameter>
		<height>3.33</height>
	</hole>
	<hole>
		<borePosition>135.7</borePosition>
		<diameter>7.76</diameter>
		<height>3.33</height>
	</hole>
	<hole>
		<borePosition>167.2</borePosition>
		<diameter>7.76</diameter>
		<height>3.33</height>
	</hole>
	<hole>
		<borePosition>198.7</borePosition>
		<diameter>7.76</diameter>
		<height>3.33</height>
	</hole>
	<hole>
		<borePosition>230.2</borePosition>
		<diameter>7.76</diameter>
		<height>3.33</height>
	</hole>
	<hole>
		<borePosition>261.7</borePosition>
		<diameter>7.76</diameter>
		<height>3.33</height>
	</hole>
	<termination>
		<flangeDiameter>28.36</flangeDiameter>
	</termination>
</wii:instrument>

=== Nodling/WWIDesigner/WWIDesigner/src/test/com/wwidesigner/optimization/example/6HoleNAF1.xml
<?xml version="1.0" encoding="UTF-8"?>
<wii:instrument xmlns:wii="http://www.wwidesigner.com/Instrument"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.wwidesigner.com/Instrument ../../../../../main/com/wwidesigner/geometry/bind/Instrument.xsd ">
	<name>6 hole NAF1</name>
	<description>Straight bore NAF with 6 holes</description>
	<lengthType>in</lengthType>
	<mouthpiece>
		<position>0.20</position>
		<fipple>
			<windowLength>0.17</windowLength>
			<windowWidth>0.68</windowWidth>
			<fippleFactor>0.55</fippleFactor>
		</fipple>
	</mouthpiece>
	<borePoint>
		<borePosition>0</borePosition>
		<boreDiameter>1.028</boreDiameter>
	</borePoint>
	<borePoint>
		<borePosition>11.97</borePosition>
		<boreDiameter>1.041</boreDiameter>
	</borePoint>
	<hole>
		<borePosition>3.15</borePosition>
		<diameter>0.308</diameter>
		<height>0.165</height>
	</hole>
	<hole>
		<borePosition>4.0</borePosition>
		<diameter>0.361</diameter>
		<height>0.165</height>
	</hole>
	<hole>
		<borePosition>4.85</borePosition>
		<diameter>0.352</diameter>
		<height>0.165</height>
	</hole>
	<hole>
		<borePosition>5.9</borePosition>
		<diameter>0.357</diameter>
		<height>0.165</height>
	</hole>
	<hole>
		<borePosition>7.0</borePosition>
		<diameter>0.379</diameter>
		<height>0.165</height>
	</hole>
	<hole>
		<borePosition>8.1</borePosition>
		<diameter>0.398</diameter>
		<height>0.165</height>
	</hole>
	<termination>
		<flangeDiameter>1.541</flangeDiameter>
	</termination>
</wii:instrument>

=== Nodling/WWIDesigner/WWIDesigner/src/test/com/wwidesigner/optimization/example/NoHoleTaperNAF.xml
<?xml version="1.0" encoding="UTF-8"?>
<wii:instrument xmlns:wii="http://www.wwidesigner.com/Instrument"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.wwidesigner.com/Instrument ../../../../../main/com/wwidesigner/geometry/bind/Instrument.xsd ">
	<name>No hole NAF with taper</name>
	<description>Tapered bore NAF with no holes</description>
	<lengthType>in</lengthType>
	<mouthpiece>
		<position>0.18</position>
		<fipple>
			<windowLength>0.15</windowLength>
			<windowWidth>0.693</windowWidth>
			<fippleFactor>0.882</fippleFactor>
		</fipple>
	</mouthpiece>
	<borePoint>
		<borePosition>0</borePosition>
		<boreDiameter>1.079</boreDiameter>
	</borePoint>
	<borePoint>
		<borePosition>8.2</borePosition>
		<boreDiameter>1.078</boreDiameter>
	</borePoint>
	<borePoint>
		<borePosition>11.8</borePosition>
		<boreDiameter>1.022</boreDiameter>
	</borePoint>
	<borePoint>
		<borePosition>17.19</borePosition>
		<boreDiameter>1.029</boreDiameter>
	</borePoint>
	<termination>
		<flangeDiameter>1.420</flangeDiameter>
	</termination>
</wii:instrument>

=== Nodling/WWIDesigner/WWIDesigner/src/test/com/wwidesigner/optimization/example/NoHoleNAF1.xml
<?xml version="1.0" encoding="UTF-8"?>
<wii:instrument xmlns:wii="http://www.wwidesigner.com/Instrument"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.wwidesigner.com/Instrument ../../../../../main/com/wwidesigner/geometry/bind/Instrument.xsd ">
	<name>No hole NAF1</name>
	<description>Straight bore NAF with no holes</description>
	<lengthType>in</lengthType>
	<mouthpiece>
		<position>0.20</position>
		<fipple>
			<windowLength>0.17</windowLength>
			<windowWidth>0.68</windowWidth>
			<fippleFactor>0.800</fippleFactor>
			<windowHeight>0.3</windowHeight>
			<windwayHeight>0.031</windwayHeight>
		</fipple>
		<beta>0.3</beta>
	</mouthpiece>
	<borePoint>
		<borePosition>0</borePosition>
		<boreDiameter>1.028</boreDiameter>
	</borePoint>
	<borePoint>
		<borePosition>11.97</borePosition>
		<boreDiameter>1.041</boreDiameter>
	</borePoint>
	<termination>
		<flangeDiameter>1.041</flangeDiameter>
	</termination>
</wii:instrument>
