=== Nodling/WWIDesigner/WWIDesigner/src/main/com/wwidesigner/geometry/bind/Instrument2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:wii="http://www.wwidesigner.com/Instrument" targetNamespace="http://www.wwidesigner.com/Instrument"
	elementFormDefault="unqualified">
	<xsd:complexType name="XmlInstrument">
		<xsd:annotation>
			<xsd:documentation>The physical geometry of a woodwind instrument.
				Dimensions may represent initial values subject to optimization
				or final values fixed throughout the calculations.
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="name" type="xsd:string" />
			<xsd:element name="description" type="xsd:string"
				minOccurs="0" />
			<xsd:element name="lengthType" type="wii:XmlLengthType">
				<xsd:annotation>
					<xsd:documentation>Units of measurement, applied to all dimensions.
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="mouthpiece" type="wii:XmlMouthpiece"
				minOccurs="0">
				<xsd:annotation>
					<xsd:documentation>Description of the "drive" end.
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:choice>
				<xsd:element name="boreDiameter" type="wii:XmlMoreThanZero">
					<xsd:annotation>
						<xsd:documentation>Inside diameter for uniform cylindrical bore.
						</xsd:documentation>
					</xsd:annotation>
				</xsd:element>
				<xsd:element name="borePoint" type="wii:XmlBorePoint"
					maxOccurs="unbounded">
					<xsd:annotation>
						<xsd:documentation>Sequence of inside diameter
							measurements for non-uniform bore,
							from fipple, cork or other head-end termination,
							to bottom-end.  Assume segments between bore points
							are conical, with linear increase in diameter.
						</xsd:documentation>
					</xsd:annotation>
				</xsd:element>
			</xsd:choice>
			<xsd:element name="hole" type="wii:XmlHole" maxOccurs="unbounded">
				<xsd:annotation>
					<xsd:documentation>Hole specifications for toneholes,
							from mouthpiece to bottom-end.
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="termination" type="wii:XmlTermination">
				<xsd:annotation>
					<xsd:documentation>Description of bottom end.
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="played" type="wii:XmlPlayingConfig"
				minOccurs="0" maxOccurs="unbounded">
				<xsd:annotation>
					<xsd:documentation>List of possible playing configurations,
						with expected or measured responses.
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:simpleType name="XmlLengthType">
		<xsd:annotation>
			<xsd:documentation>Units of measurement, applied globally to all
				Dimensions, indicating mm or inch values.
			</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="xsd:token">
			<xsd:enumeration value="mm" />
			<xsd:enumeration value="in" />
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="XmlOptimization">
		<xsd:annotation>
			<xsd:documentation>An enumeration, applied individually to all
				Dimension values, that is interpreted by the optimization engine. We
				might want to add other/additional values to this enumeration.
			</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="xsd:token">
			<xsd:enumeration value="FIXED" />
			<xsd:enumeration value="FREE" />
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:complexType name="XmlDimension">
		<xsd:annotation>
			<xsd:documentation>Base class for a double value and associated
				optimization flag.
			</xsd:documentation>
		</xsd:annotation>
		<xsd:simpleContent>
		    <xsd:extension base="xsd:double">
				<xsd:attribute name="optimization" type="wii:XmlOptimization" default="FIXED">
				</xsd:attribute>
			</xsd:extension>
		</xsd:simpleContent>
	</xsd:complexType>

	<xsd:complexType name="XmlZeroOrMore">
		<xsd:annotation>
			<xsd:documentation>A non-negative Dimension.</xsd:documentation>
		</xsd:annotation>
		<xsd:simpleContent>
			<xsd:restriction base="wii:XmlDimension">
				<xsd:minInclusive value="0" />
			</xsd:restriction>
		</xsd:simpleContent>
	</xsd:complexType>

	<xsd:complexType name="XmlMoreThanZero">
		<xsd:annotation>
			<xsd:documentation>A Dimension with a value greater than 0.
			</xsd:documentation>
		</xsd:annotation>
		<xsd:simpleContent>
			<xsd:restriction base="wii:XmlDimension">
				<xsd:minExclusive value="0" />
			</xsd:restriction>
		</xsd:simpleContent>
	</xsd:complexType>

	<xsd:complexType name="XmlMouthpiece">
		<xsd:annotation>
			<xsd:documentation>Draft sound-mechanism model. Represents
				a choice between (1) a characteristic length, (2) a flute-type
				embouchure hole, or (3) a fipple window and sound blade. We need to add reeds,
				end-blown flutes, etc.
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="position" type="wii:XmlZeroOrMore">
				<xsd:annotation>
					<xsd:documentation>Position of sound-blade for fipple flute,
						centre of embouchure hole for transverse flute,
						measured from bottom end.
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:choice>
				<xsd:element name="characteristicLength" type="wii:XmlMoreThanZero" />
				<xsd:element name="embouchureHole">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="innerDiameter" type="wii:XmlMoreThanZero">
								<xsd:annotation>
									<xsd:documentation>Equivalent diameter of hole inside the tube.
									</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="outerDiameter" type="wii:XmlMoreThanZero">
								<xsd:annotation>
									<xsd:documentation>Equivalent diameter of hole outside the tube.
									</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="height" type="wii:XmlMoreThanZero">
								<xsd:annotation>
									<xsd:documentation>Chimney height of hole, from inside to outsides.
									</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="lengthToCork" type="wii:XmlMoreThanZero">
								<xsd:annotation>
									<xsd:documentation>Distance from centre of embouchure hole
										to closed head end.
									</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="fipple">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="windowLength" type="wii:XmlMoreThanZero">
								<xsd:annotation>
									<xsd:documentation>Distance from fipple to sound blade.
									</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="windowWidth" type="wii:XmlMoreThanZero">
								<xsd:annotation>
									<xsd:documentation>Side-to-side width of window.
									</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="windowHeight" type="wii:XmlMoreThanZero">
								<xsd:annotation>
									<xsd:documentation>Average "height" of window,
										between inside and outside of tube.
									</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="windwayLength" type="wii:XmlMoreThanZero">
								<xsd:annotation>
									<xsd:documentation>Length of windway, from beak to exit.
									</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="windwayHeight" type="wii:XmlMoreThanZero">
								<xsd:annotation>
									<xsd:documentation>Average height of windway at the exit.
									</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
			</xsd:choice>
			<xsd:element name="beta" type="wii:XmlZeroOrMore">
				<xsd:annotation>
					<xsd:documentation>Jet spatial amplification factor.
						See Auvray, et al., "Regime change and oscillation thresholds
						in recorder-like instruments", J. Acoust. Soc. Am. 131 (2), February 2012
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="XmlBorePoint">
		<xsd:annotation>
			<xsd:documentation>Represents a bore position and effective inside diameter,
				measured from the bottom end of the instrument. Diameters between
				borePoints are linearly interpolated.
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="borePosition" type="wii:XmlZeroOrMore" />
			<xsd:element name="boreDiameter" type="wii:XmlZeroOrMore" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="XmlHole">
		<xsd:annotation>
			<xsd:documentation>A tone hole with optional key mechanism. The tone
				hole assumes a cylindrical shape with a radiused inner edge. More
				complexity is possible, including truncated conical profiles and
				angled holes.
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="name" type="xsd:string" minOccurs="0" />
			<xsd:element name="position" type="wii:XmlZeroOrMore" />
			<xsd:element name="diameter" type="wii:XmlMoreThanZero" />
			<xsd:element name="height" type="wii:XmlMoreThanZero" />
			<xsd:element name="innerCurvatureRadius" type="wii:XmlZeroOrMore"
				minOccurs="0" />
			<xsd:element name="key" type="wii:XmlKey" minOccurs="0" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="XmlKey">
		<xsd:annotation>
			<xsd:documentation>Representation of a key mechanism over a tone
				hole.
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="diameter" type="wii:XmlMoreThanZero" />
			<xsd:element name="holeDiameter" type="wii:XmlZeroOrMore" />
			<xsd:element name="height" type="wii:XmlZeroOrMore" />
			<xsd:element name="thickness" type="wii:XmlZeroOrMore" />
			<xsd:element name="wallThickness" type="wii:XmlZeroOrMore" />
			<xsd:element name="chimneyHeight" type="wii:XmlZeroOrMore" />
			<xsd:element name="normally" type="wii:XmlHoleState" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="XmlTermination">
		<xsd:annotation>
			<xsd:documentation>Description of the opening at the bottom end of the instrument.
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="flangeDiameter" type="wii:XmlZeroOrMore">
				<xsd:annotation>
					<xsd:documentation>Outer diameter of the open end.
						Zero if the bottom end is closed.
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:simpleType name="XmlHoleState">
		<xsd:annotation>
			<xsd:documentation>Description of a tonehole state: 0 for open, 1 for closed.
			</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="xsd:integer">
			<xsd:enumeration value="0" />
			<xsd:enumeration value="1" />
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="XmlFingering">
		<xsd:annotation>
			<xsd:documentation>List of tonehole states, from mouthpiece to bottom end.
			</xsd:documentation>
		</xsd:annotation>
		<xsd:list itemType="wii:XmlHoleState" />
	</xsd:simpleType>

	<xsd:simpleType name="XmlPitch">
		<xsd:annotation>
			<xsd:documentation>Non-zero frequency, in Hz.
			</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="xsd:double">
			<xsd:minExclusive value="0" />
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="XmlListOfPitches">
		<xsd:annotation>
			<xsd:documentation>List of playing frequencies, in Hz.
			</xsd:documentation>
		</xsd:annotation>
		<xsd:list itemType="wii:XmlPitch" />
	</xsd:simpleType>

	<xsd:complexType name="XmlPlayingConfig">
		<xsd:annotation>
			<xsd:documentation>Description of a playing configuration for the instrument,
				with the intended and measured responses for that playing configuration.
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="fingers" type="wii:XmlFingering">
				<xsd:annotation>
					<xsd:documentation>Description of playing configuration.
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="embouchure" type="wii:XmlMoreThanZero" minOccurs="0">
				<xsd:annotation>
					<xsd:documentation>Distance from lips to edge of embouchure hole.
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="target" type="wii:XmlListOfPitches">
				<xsd:annotation>
					<xsd:documentation>Target pitches expected from this playing configuration.
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="fmin" type="wii:XmlListOfPitches">
				<xsd:annotation>
					<xsd:documentation>Measured actual minimum frequencies
						for playing ranges of this configuration. 
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="fmax" type="wii:XmlListOfPitches">
				<xsd:annotation>
					<xsd:documentation>Measured actual maximum frequencies
						for playing ranges of this configuration. 
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:element name="instrument" type="wii:XmlInstrument" />
</xsd:schema>

=== Nodling/WWIDesigner/WWIDesigner/src/main/com/wwidesigner/geometry/bind/example/BP7.xml
<?xml version="1.0" encoding="utf-8"?>
<wii:instrument xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns:wii="http://www.wwidesigner.com/Instrument"
         xsi:schemaLocation="http://www.wwidesigner.com/Instrument ../Instrument2.xsd ">
	<name>BP7 Whistle</name>
	<description>6-hole PVC whistle, high D, A=440 Just Intonation</description>
	<lengthType>mm</lengthType>
	<mouthpiece>
		<position>267.5</position>
		<fipple>
			<windowLength>5.4</windowLength>
			<windowWidth>6.5</windowWidth>
			<windowHeight>3.6</windowHeight>
			<windwayLength>21.</windwayLength>
			<windwayHeight>1.36</windwayHeight>
		</fipple>
		<beta>0.4</beta>
	</mouthpiece>
	<boreDiameter>11.9</boreDiameter>
	<hole>
		<position optimization="FREE">150.5</position>
		<diameter optimization="FREE">5.6</diameter>
		<height>2.0</height>
	</hole>
	<hole>
		<position optimization="FREE">128.0</position>
		<diameter optimization="FREE">6.0</diameter>
		<height>2.0</height>
	</hole>
	<hole>
		<position optimization="FREE">109.0</position>
		<diameter optimization="FREE">6.0</diameter>
		<height>2.0</height>
	</hole>
	<hole>
		<position optimization="FREE">81.0</position>
		<diameter optimization="FREE">6.0</diameter>
		<height>2.0</height>
	</hole>
	<hole>
		<position optimization="FREE">64.5</position>
		<diameter optimization="FREE">7.9</diameter>
		<height>2.0</height>
	</hole>
	<hole>
		<position optimization="FREE">40.0</position>
		<diameter optimization="FREE">7.5</diameter>
		<height>2.0</height>
	</hole>
	<termination>
		<flangeDiameter>15.9</flangeDiameter>
	</termination>
</wii:instrument>
