=== Nodling/WWIDesigner/WWIDesigner/src/main/com/wwidesigner/geometry/Instrument.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:ekf="http://www.wwidesigner.com/Instrument" targetNamespace="http://www.wwidesigner.com/Instrument"
	elementFormDefault="unqualified">
	<xs:complexType name="Instrument">
		<xs:sequence>
			<xs:element name="lengthType" type="ekf:LengthType" />
			<xs:element name="embouchure" type="ekf:Embouchure"
				minOccurs="0" />
			<xs:element name="borePoint" type="ekf:BorePoint"
				maxOccurs="unbounded" />
			<xs:element name="termination" type="ekf:EndBoreSection" />
		</xs:sequence>
		<xs:attribute name="description" type="xs:string" use="optional" />
	</xs:complexType>

	<xs:simpleType name="LengthType">
		<xs:restriction base="xs:token">
			<xs:enumeration value="mm" />
			<xs:enumeration value="in" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="zeroOrMore">
		<xs:restriction base="xs:double">
			<xs:minInclusive value="0" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="moreThanZero">
		<xs:restriction base="xs:double">
			<xs:minExclusive value="0" />
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="BorePoint">
		<xs:sequence>
			<xs:element name="borePosition" type="ekf:zeroOrMore" />
			<xs:element name="boreDiameter" type="ekf:zeroOrMore" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="EndBoreSection">
		<xs:sequence>
			<xs:element name="flangeDiameter" type="ekf:moreThanZero" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="Embouchure">
		<xs:sequence>
			<xs:element name="backSet" type="ekf:zeroOrMore" />
			<xs:choice>
				<xs:element name="characteristicLength" type="ekf:moreThanZero" />
				<xs:sequence>
					<xs:element name="tshWidth" type="ekf:moreThanZero" />
					<xs:element name="tshLength" type="ekf:moreThanZero" />
					<xs:element name="birdFactor" type="ekf:moreThanZero" />
				</xs:sequence>
			</xs:choice>
		</xs:sequence>
	</xs:complexType>

	<xs:element name="instrument" type="ekf:Instrument" />
</xs:schema>

=== Nodling/WWIDesigner/WWIDesigner/src/main/com/wwidesigner/impedance/geometry/Instrument.xml
<?xml version="1.0" encoding="UTF-8"?>
<ekf:instrument description="" xmlns:ekf="http://www.wwidesigner.com/Instrument" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.wwidesigner.com/Instrument Instrument.xsd ">
  <lengthType>mm</lengthType>
  <embouchure>
    <backSet>0.0</backSet>
    <characteristicLength>5.0</characteristicLength>
  </embouchure>
  <borePoint>
    <borePosition>0.0</borePosition>
    <boreDiameter>0.0</boreDiameter>
  </borePoint>
  <termination>
    <flangeDiameter>1.0</flangeDiameter>
  </termination>
</ekf:instrument>
