=== Nodling/WWIDesigner/WWIDesigner/src/main/com/wwidesigner/optimization/bind/Constraints.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.wwidesigner.com/Constraints" xmlns:wic="http://www.wwidesigner.com/Constraints"
	elementFormDefault="unqualified">

	<xsd:element name="constraints" type="wic:Constraints" />

	<xsd:complexType name="Constraints">
		<xsd:annotation>
			<xsd:documentation>The bounds and metadata for an optimizer
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="constraintsName" type="xsd:string" />
			<xsd:element name="objectiveDisplayName" type="xsd:string" />
			<xsd:element name="objectiveFunctionName" type="xsd:string" />
			<xsd:element name="numberOfHoles" type="xsd:integer" />
			<xsd:element name="constraint" type="wic:Constraint"
				minOccurs="0" maxOccurs="unbounded" />
			<xsd:element name="holeGroups" type="wic:HoleGroups"
				minOccurs="0" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="Constraint">
		<xsd:annotation>
			<xsd:documentation>The metadata for a single-value constraint
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="displayName" type="xsd:string" />
			<xsd:element name="category" type="xsd:string" />
			<xsd:element name="type" type="wic:ConstraintType" />
			<xsd:element name="lowerBound" type="xsd:double"
				minOccurs="0" />
			<xsd:element name="upperBound" type="xsd:double"
				minOccurs="0" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:simpleType name="ConstraintType">
		<xsd:annotation>
			<xsd:documentation>An enumeration defining the type of constraint.
				Currently, only DIMENSIONAL and DIMENSIONLESS are implemented.
			</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="xsd:token">
			<xsd:enumeration value="BOOLEAN" />
			<xsd:enumeration value="INTEGER" />
			<xsd:enumeration value="DIMENSIONAL" />
			<xsd:enumeration value="DIMENSIONLESS" />
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:complexType name="HoleGroups">
		<xsd:annotation>
			<xsd:documentation>A list of contiguous finger holes groups
				constrained to
				have the same inter-hole spacing.
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="holeGroup" type="wic:HoleGroup"
				minOccurs="0" maxOccurs="unbounded" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="HoleGroup">
		<xsd:annotation>
			<xsd:documentation>A list of contiguous finger hole indices
				constrained to have the same inter-hole spacing.
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="holeIdx" type="xsd:integer" maxOccurs="unbounded" />
		</xsd:sequence>
	</xsd:complexType>

</xsd:schema>

=== Nodling/WWIDesigner/WWIDesigner/src/test/com/wwidesigner/optimization/example/7-hole_broad-constraints.xml
<?xml version="1.0" encoding="UTF-8"?>
<wic:constraints xmlns:wic="http://www.wwidesigner.com/Constraints"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.wwidesigner.com/Constraints ../bind/Constraints.xsd ">
	<constraintsName>Broad-span bounds, 2 triplets of hole groups</constraintsName>
	<objectiveDisplayName>Single taper, grouped-hole optimizer</objectiveDisplayName>
	<objectiveFunctionName>com.wwidesigner.optimization.SingleTaperHoleGroupObjectiveFunction</objectiveFunctionName>
	<numberOfHoles>7</numberOfHoles>
  	<constraint>
		<displayName>Bore length</displayName>
		<category>Hole position</category>
		<type>DIMENSIONAL</type>
		<lowerBound>0.2</lowerBound>
		<upperBound>0.7</upperBound>
	</constraint>
	<constraint>
		<displayName>Group 1 (Hole 7 (top), Hole 6, Hole 5) spacing</displayName>
		<category>Hole position</category>
		<type>DIMENSIONAL</type>
		<lowerBound>0.01</lowerBound>
		<upperBound>0.04</upperBound>
	</constraint>
	<constraint>
		<displayName>Hole 5 to Hole 4 distance</displayName>
		<category>Hole position</category>
		<type>DIMENSIONAL</type>
		<lowerBound>0.012</lowerBound>
		<upperBound>0.05</upperBound>
	</constraint>
	<constraint>
		<displayName>Group 2 (Hole 4, Hole 3, Hole 2) spacing</displayName>
		<category>Hole position</category>
		<type>DIMENSIONAL</type>
		<lowerBound>0.012</lowerBound>
		<upperBound>0.05</upperBound>
	</constraint>
	<constraint>
		<displayName>Hole 2 to Hole 1 (bottom) distance</displayName>
		<category>Hole position</category>
		<type>DIMENSIONAL</type>
		<lowerBound>0.012</lowerBound>
		<upperBound>0.1</upperBound>
	</constraint>
	<constraint>
		<displayName>Hole 1 (bottom) to bore end distance</displayName>
		<category>Hole position</category>
		<type>DIMENSIONAL</type>
		<lowerBound>0.012</lowerBound>
		<upperBound>0.3</upperBound>
	</constraint>
	<constraint>
		<displayName>Hole 7 (top) diameter</displayName>
		<category>Hole size</category>
		<type>DIMENSIONAL</type>
		<lowerBound>0.002</lowerBound>
		<upperBound>0.14</upperBound>
	</constraint>
	<constraint>
		<displayName>Hole 6 diameter</displayName>
		<category>Hole size</category>
		<type>DIMENSIONAL</type>
		<lowerBound>0.002</lowerBound>
		<upperBound>0.14</upperBound>
	</constraint>
	<constraint>
		<displayName>Hole 5 diameter</displayName>
		<category>Hole size</category>
		<type>DIMENSIONAL</type>
		<lowerBound>0.002</lowerBound>
		<upperBound>0.14</upperBound>
	</constraint>
	<constraint>
		<displayName>Hole 4 diameter</displayName>
		<category>Hole size</category>
		<type>DIMENSIONAL</type>
		<lowerBound>0.002</lowerBound>
		<upperBound>0.14</upperBound>
	</constraint>
	<constraint>
		<displayName>Hole 3 diameter</displayName>
		<category>Hole size</category>
		<type>DIMENSIONAL</type>
		<lowerBound>0.002</lowerBound>
		<upperBound>0.14</upperBound>
	</constraint>
	<constraint>
		<displayName>Hole 2 diameter</displayName>
		<category>Hole size</category>
		<type>DIMENSIONAL</type>
		<lowerBound>0.002</lowerBound>
		<upperBound>0.15</upperBound>
	</constraint>
	<constraint>
		<displayName>Hole 1 (bottom) diameter</displayName>
		<category>Hole size</category>
		<type>DIMENSIONAL</type>
		<lowerBound>0.002</lowerBound>
		<upperBound>0.15</upperBound>
	</constraint>
	<constraint>
		<displayName>Bore diameter ratio (top/bottom)</displayName>
		<category>Single bore taper</category>
		<type>DIMENSIONLESS</type>
		<lowerBound>0.5</lowerBound>
		<upperBound>2.0</upperBound>
	</constraint>
	<constraint>
		<displayName>Taper length ratio (to bore length)</displayName>
		<category>Single bore taper</category>
		<type>DIMENSIONLESS</type>
		<lowerBound>0.0</lowerBound>
		<upperBound>1.0</upperBound>
	</constraint>
	<constraint>
		<displayName>Taper start ratio (from top/untapered length)</displayName>
		<category>Single bore taper</category>
		<type>DIMENSIONLESS</type>
		<lowerBound>0.0</lowerBound>
		<upperBound>1.0</upperBound>
	</constraint>
</wic:constraints>
