=== Nodling/WWIDesigner/WWIDesigner/src/main/com/wwidesigner/note/bind/Tuning.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.wwidesigner.com/Tuning" xmlns:wit="http://www.wwidesigner.com/Tuning"
	elementFormDefault="unqualified">

	<xsd:element name="temperament" type="wit:XmlTemperament">
		<xsd:annotation>
			<xsd:documentation>Persistent/reusable temperament
			</xsd:documentation>
		</xsd:annotation>
	</xsd:element>

	<xsd:element name="scaleSymbolList" type="wit:XmlScaleSymbolList">
		<xsd:annotation>
			<xsd:documentation>Persistent/reusable list of note symbols
			</xsd:documentation>
		</xsd:annotation>
	</xsd:element>

	<xsd:element name="scale" type="wit:XmlScale">
		<xsd:annotation>
			<xsd:documentation>Persistent/reusable scale</xsd:documentation>
		</xsd:annotation>
	</xsd:element>

	<xsd:element name="fingeringPattern" type="wit:XmlFingeringPattern"/>

	<xsd:element name="tuning" type="wit:XmlTuning"/>

	<xsd:complexType name="XmlScale">
		<xsd:annotation>
			<xsd:documentation>Named list of Notes</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="name" type="xsd:string"/>
			<xsd:element name="comment" type="xsd:string" maxOccurs="1" minOccurs="0"/>
			<xsd:element name="note" maxOccurs="unbounded"
				minOccurs="1">
				<xsd:complexType>
					<xsd:complexContent>
						<xsd:restriction base="wit:XmlNote">
							<xsd:sequence>
								<xsd:element name="name"
									type="xsd:string" />
								<xsd:element name="frequency"
									type="xsd:double" minOccurs="1" maxOccurs="1" />
							</xsd:sequence>
						</xsd:restriction>
					</xsd:complexContent>
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="XmlNote">
		<xsd:annotation>
			<xsd:documentation>Name/frequency pair</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="name" type="xsd:string"/>
			<xsd:element name="frequency" type="xsd:double"
				maxOccurs="1" minOccurs="0"/>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="XmlTemperament">
		<xsd:annotation>
			<xsd:documentation>Named list of intervals relative to the root
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="name" type="xsd:string"/>
			<xsd:element name="comment" type="xsd:string" maxOccurs="1" minOccurs="0"/>
			<xsd:element name="interval" type="wit:XmlOneOrMore"
				maxOccurs="unbounded" minOccurs="1" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:simpleType name="XmlOneOrMore">
		<xsd:annotation>
			<xsd:documentation>Number greater than or equal to 1.
			</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="xsd:double">
			<xsd:minInclusive value="1"/>
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:complexType name="XmlScaleSymbolList">
		<xsd:annotation>
			<xsd:documentation>Named list of note symbols</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="name" type="xsd:string"/>
			<xsd:element name="comment" type="xsd:string" maxOccurs="1" minOccurs="0"/>
			<xsd:element name="scaleSymbol" type="xsd:string"
				maxOccurs="unbounded" minOccurs="1" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="XmlFingeringPattern">
		<xsd:sequence>
			<xsd:element name="name" type="xsd:string"/>
			<xsd:element name="comment" type="xsd:string" maxOccurs="1" minOccurs="0"/>
			<xsd:element name="numberOfHoles"
				type="xsd:nonNegativeInteger" />
			<xsd:sequence>
				<xsd:element name="fingering" type="wit:XmlFingering"
					maxOccurs="unbounded" minOccurs="0" />
			</xsd:sequence>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="XmlFingering">
		<xsd:sequence>
			<xsd:element name="note" type="wit:XmlNote" maxOccurs="1"
				minOccurs="0"/>
			<xsd:sequence>
				<xsd:element name="openHole" type="xsd:boolean"
					maxOccurs="unbounded" minOccurs="0"/>
			</xsd:sequence>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="XmlTuning">
		<xsd:complexContent>
			<xsd:restriction base="wit:XmlFingeringPattern">
				<xsd:sequence>
					<xsd:element name="name" type="xsd:string"/>
					<xsd:element name="comment" type="xsd:string" maxOccurs="1" minOccurs="0"/>
					<xsd:element name="numberOfHoles"
						type="xsd:nonNegativeInteger" />
					<xsd:sequence>
						<xsd:element name="fingering"
							maxOccurs="unbounded" minOccurs="1">
							<xsd:complexType>
								<xsd:complexContent>
									<xsd:restriction
										base="wit:XmlFingering">
										<xsd:sequence>
											<xsd:element name="note"
												maxOccurs="1" minOccurs="1">
												<xsd:complexType>
													<xsd:complexContent>
														<xsd:restriction
															base="wit:XmlNote">
															<xsd:sequence>
																<xsd:element
																	name="name" type="xsd:string" />
																<xsd:element
																	name="frequency" type="xsd:double" maxOccurs="1"
																	minOccurs="1" />
															</xsd:sequence>
														</xsd:restriction>
													</xsd:complexContent>
												</xsd:complexType>
											</xsd:element>
											<xsd:sequence>
												<xsd:element
													name="openHole" type="xsd:boolean" maxOccurs="unbounded"
													minOccurs="0" />
											</xsd:sequence>
										</xsd:sequence>
									</xsd:restriction>
								</xsd:complexContent>
							</xsd:complexType>
						</xsd:element>
					</xsd:sequence>
				</xsd:sequence>
			</xsd:restriction>
		</xsd:complexContent>
	</xsd:complexType>

</xsd:schema>

=== Nodling/WWIDesigner/WWIDesigner/releases/1/WhistleStudy/tunings/Bb4-Just.xml
<?xml version="1.0" encoding="utf-8"?>
<wit:tuning xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns:wit="http://www.wwidesigner.com/Tuning"
         xsi:schemaLocation="http://www.wwidesigner.com/Tuning ../Tuning.xsd ">

	<name>Alto Bb JI Tuning</name>
	<comment>6-hole whistle, alto Bb, Just Intonation tuning.</comment>
	<numberOfHoles>6</numberOfHoles>
	<fingering>
		<note>
			<name>Bb</name>
			<frequency>466.16</frequency>
		</note>
		<openHole>false</openHole><openHole>false</openHole><openHole>false</openHole>
		<openHole>false</openHole><openHole>false</openHole><openHole>false</openHole>
	</fingering>
	<fingering>
		<note>
			<name>C</name>
			<frequency>524.43</frequency>
		</note>
		<openHole>false</openHole><openHole>false</openHole><openHole>false</openHole>
		<openHole>false</openHole><openHole>false</openHole><openHole>true</openHole>
	</fingering>
	<fingering>
		<note>
			<name>D</name>
			<frequency>582.70</frequency>
		</note>
		<openHole>false</openHole><openHole>false</openHole><openHole>false</openHole>
		<openHole>false</openHole><openHole>true</openHole><openHole>true</openHole>
	</fingering>
	<fingering>
		<note>
			<name>Eb</name>
			<frequency>621.55</frequency>
		</note>
		<openHole>false</openHole><openHole>false</openHole><openHole>false</openHole>
		<openHole>true</openHole><openHole>true</openHole><openHole>true</openHole>
	</fingering>
	<fingering>
		<note>
			<name>F</name>
			<frequency>699.25</frequency>
		</note>
		<openHole>false</openHole><openHole>false</openHole><openHole>true</openHole>
		<openHole>true</openHole><openHole>true</openHole><openHole>true</openHole>
	</fingering>
	<fingering>
		<note>
			<name>G</name>
			<frequency>776.94</frequency>
		</note>
		<openHole>false</openHole><openHole>true</openHole><openHole>true</openHole>
		<openHole>true</openHole><openHole>true</openHole><openHole>true</openHole>
	</fingering>
	<fingering>
		<note>
			<name>Ab</name>
			<frequency>828.74</frequency>
		</note>
		<openHole>true</openHole><openHole>false</openHole><openHole>false</openHole>
		<openHole>true</openHole><openHole>true</openHole><openHole>true</openHole>
	</fingering>
	<fingering>
		<note>
			<name>A</name>
			<frequency>874.06</frequency>
		</note>
		<openHole>true</openHole><openHole>true</openHole><openHole>true</openHole>
		<openHole>true</openHole><openHole>true</openHole><openHole>true</openHole>
	</fingering>
	<fingering>
		<note>
			<name>Bb</name>
			<frequency>932.33</frequency>
		</note>
		<openHole>true</openHole><openHole>false</openHole><openHole>false</openHole>
		<openHole>false</openHole><openHole>false</openHole><openHole>false</openHole>
	</fingering>
	<fingering>
		<note>
			<name>C</name>
			<frequency>1048.9</frequency>
		</note>
		<openHole>false</openHole><openHole>false</openHole><openHole>false</openHole>
		<openHole>false</openHole><openHole>false</openHole><openHole>true</openHole>
	</fingering>
	<fingering>
		<note>
			<name>D</name>
			<frequency>1165.4</frequency>
		</note>
		<openHole>false</openHole><openHole>false</openHole><openHole>false</openHole>
		<openHole>false</openHole><openHole>true</openHole><openHole>true</openHole>
	</fingering>
	<fingering>
		<note>
			<name>Eb</name>
			<frequency>1243.1</frequency>
		</note>
		<openHole>false</openHole><openHole>false</openHole><openHole>false</openHole>
		<openHole>true</openHole><openHole>true</openHole><openHole>true</openHole>
	</fingering>
	<fingering>
		<note>
			<name>F</name>
			<frequency>1398.5</frequency>
		</note>
		<openHole>false</openHole><openHole>false</openHole><openHole>true</openHole>
		<openHole>true</openHole><openHole>true</openHole><openHole>true</openHole>
	</fingering>
	<fingering>
		<note>
			<name>G</name>
			<frequency>1553.9</frequency>
		</note>
		<openHole>false</openHole><openHole>true</openHole><openHole>true</openHole>
		<openHole>true</openHole><openHole>true</openHole><openHole>true</openHole>
	</fingering>
	<fingering>
		<note>
			<name>Ab</name>
			<frequency>1657.5</frequency>
		</note>
		<openHole>true</openHole><openHole>false</openHole><openHole>true</openHole>
		<openHole>false</openHole><openHole>false</openHole><openHole>false</openHole>
	</fingering>
	<fingering>
		<note>
			<name>A</name>
			<frequency>1748.1</frequency>
		</note>
		<openHole>true</openHole><openHole>true</openHole><openHole>true</openHole>
		<openHole>true</openHole><openHole>true</openHole><openHole>true</openHole>
	</fingering>
	<fingering>
		<note>
			<name>Bb</name>
			<frequency>1864.7</frequency>
		</note>
		<openHole>true</openHole><openHole>false</openHole><openHole>false</openHole>
		<openHole>true</openHole><openHole>true</openHole><openHole>true</openHole>
	</fingering>
</wit:tuning>

=== Nodling/WWIDesigner/WWIDesigner/src/test/com/wwidesigner/modelling/example/NAF_D_minor_cherry_actual_tuning.xml
<?xml version="1.0" encoding="UTF-8"?>
<wit:tuning xmlns:wit="http://www.wwidesigner.com/Tuning"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.wwidesigner.com/Tuning ../../../../../main/com/wwidesigner/note/bind/Tuning.xsd ">
	<name>D minor ET,6 hole NAF tuning, Cherry2 actual</name>
	<comment>D minor equal temperament tuning for 6-hole NAF. Actual tuning for Cherry2 NAF with initial small holes.</comment>
	<numberOfHoles>6</numberOfHoles>
	<fingering>
		<note>
			<name>D4 (D4 - 18)</name>
			<frequency>290.63</frequency>
		</note>
		<openHole>false</openHole>
		<openHole>false</openHole>
		<openHole>false</openHole>
		<openHole>false</openHole>
		<openHole>false</openHole>
		<openHole>false</openHole>
	</fingering>
	<fingering>
		<note>
			<name>F4 (E4 + 14)</name>
			<frequency>332.30</frequency>
		</note>
		<openHole>false</openHole>
		<openHole>false</openHole>
		<openHole>false</openHole>
		<openHole>false</openHole>
		<openHole>false</openHole>
		<openHole>true</openHole>
	</fingering>
 	<fingering>
		<note>
			<name>F#4 (F4 - 23)</name>
			<frequency>344.62</frequency>
		</note>
		<openHole>false</openHole>
		<openHole>false</openHole>
		<openHole>false</openHole>
		<openHole>false</openHole>
		<openHole>true</openHole>
		<openHole>false</openHole>
	</fingering>  
	<fingering>
		<note>
			<name>G4 (Gb4 - 2)</name>
			<frequency>369.57</frequency>
		</note>
		<openHole>false</openHole>
		<openHole>false</openHole>
		<openHole>false</openHole>
		<openHole>false</openHole>
		<openHole>true</openHole>
		<openHole>true</openHole>
	</fingering>
	<fingering>
		<note>
			<name>G#4(G4 + 22) </name>
			<frequency>397.01</frequency>
		</note>
		<openHole>false</openHole>
		<openHole>false</openHole>
		<openHole>false</openHole>
		<openHole>true</openHole>
		<openHole>false</openHole>
		<openHole>true</openHole>
	</fingering>   
	<fingering>
		<note>
			<name>A4 (Ab4 + 2)</name>
			<frequency>415.78</frequency>
		</note>
		<openHole>false</openHole>
		<openHole>false</openHole>
		<openHole>false</openHole>
		<openHole>true</openHole>
		<openHole>true</openHole>
		<openHole>true</openHole>
	</fingering>
	<fingering>
		<note>
			<name>A#4 (Ab4 + 40)</name>
			<frequency>425.01</frequency>
		</note>
		<openHole>false</openHole>
		<openHole>false</openHole>
		<openHole>true</openHole>
		<openHole>false</openHole>
		<openHole>true</openHole>
		<openHole>true</openHole>
	</fingering>
	<fingering>
		<note>
			<name>B4 (Bb4 - 30)</name>
			<frequency>458.16</frequency>
		</note>
		<openHole>false</openHole>
		<openHole>false</openHole>
		<openHole>true</openHole>
		<openHole>true</openHole>
		<openHole>true</openHole>
		<openHole>true</openHole>
	</fingering>  
	<fingering>
		<note>
			<name>C5 (Bb4 + 22)</name>
			<frequency>472.13</frequency>
		</note>
		<openHole>false</openHole>
		<openHole>true</openHole>
		<openHole>false</openHole>
		<openHole>true</openHole>
		<openHole>true</openHole>
		<openHole>true</openHole>
	</fingering>
	<fingering>
		<note>
			<name>C#5 (B4 + 32)</name>
			<frequency>503.10</frequency>
		</note>
		<openHole>false</openHole>
		<openHole>true</openHole>
		<openHole>true</openHole>
		<openHole>true</openHole>
		<openHole>true</openHole>
		<openHole>true</openHole>
	</fingering>  
	<fingering>
		<note>
			<name>D5 (C5 + 9)</name>
			<frequency>525.98</frequency>
		</note>
		<openHole>true</openHole>
		<openHole>true</openHole>
		<openHole>false</openHole>
		<openHole>true</openHole>
		<openHole>true</openHole>
		<openHole>true</openHole>
	</fingering>
	<fingering>
		<note>
			<name>D#5 (Db5 - 1)</name>
			<frequency>554.05</frequency>
		</note>
		<openHole>true</openHole>
		<openHole>true</openHole>
		<openHole>true</openHole>
		<openHole>true</openHole>
		<openHole>true</openHole>
		<openHole>true</openHole>
	</fingering>  
	<fingering>
		<note>
			<name>E5 (Eb5 + 48)</name>
			<frequency>639.75</frequency>
		</note>
		<openHole>true</openHole>
		<openHole>true</openHole>
		<openHole>false</openHole>
		<openHole>false</openHole>
		<openHole>false</openHole>
		<openHole>false</openHole>
	</fingering>  
	<fingering>
		<note>
			<name>F5 (E5 + 25)</name>
			<frequency>668.84</frequency>
		</note>
		<openHole>true</openHole>
		<openHole>true</openHole>
		<openHole>false</openHole>
		<openHole>false</openHole>
		<openHole>false</openHole>
		<openHole>true</openHole>
	</fingering> 
</wit:tuning>

=== Nodling/WWIDesigner/WWIDesigner/src/test/com/wwidesigner/optimization/example/D_NAF_tuning.xml
<?xml version="1.0" encoding="UTF-8"?>
<wit:tuning xmlns:wit="http://www.wwidesigner.com/Tuning"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.wwidesigner.com/Tuning ../../../../../main/com/wwidesigner/note/bind/Tuning.xsd ">
	<name>D minor ET,6 hole NAF tuning</name>
	<comment>D minor equal temperament tuning for 6-hole NAF</comment>
	<numberOfHoles>6</numberOfHoles>
	<fingering>
		<note>
			<name>D4</name>
			<frequency>293.66</frequency>
		</note>
		<openHole>false</openHole>
		<openHole>false</openHole>
		<openHole>false</openHole>
		<openHole>false</openHole>
		<openHole>false</openHole>
		<openHole>false</openHole>
	</fingering>
	<fingering>
		<note>
			<name>F4</name>
			<frequency>349.23</frequency>
		</note>
		<openHole>false</openHole>
		<openHole>false</openHole>
		<openHole>false</openHole>
		<openHole>false</openHole>
		<openHole>false</openHole>
		<openHole>true</openHole>
	</fingering>
 	<fingering>
		<note>
			<name>F#4</name>
			<frequency>369.99</frequency>
		</note>
		<openHole>false</openHole>
		<openHole>false</openHole>
		<openHole>false</openHole>
		<openHole>false</openHole>
		<openHole>true</openHole>
		<openHole>false</openHole>
	</fingering>  
	<fingering>
		<note>
			<name>G4</name>
			<frequency>392.00</frequency>
		</note>
		<openHole>false</openHole>
		<openHole>false</openHole>
		<openHole>false</openHole>
		<openHole>false</openHole>
		<openHole>true</openHole>
		<openHole>true</openHole>
	</fingering>
	<fingering>
		<note>
			<name>G#4</name>
			<frequency>415.30</frequency>
		</note>
		<openHole>false</openHole>
		<openHole>false</openHole>
		<openHole>false</openHole>
		<openHole>true</openHole>
		<openHole>false</openHole>
		<openHole>true</openHole>
	</fingering>   
	<fingering>
		<note>
			<name>A4</name>
			<frequency>440.00</frequency>
		</note>
		<openHole>false</openHole>
		<openHole>false</openHole>
		<openHole>false</openHole>
		<openHole>true</openHole>
		<openHole>true</openHole>
		<openHole>true</openHole>
	</fingering>
	<fingering>
		<note>
			<name>A#4</name>
			<frequency>466.16</frequency>
		</note>
		<openHole>false</openHole>
		<openHole>false</openHole>
		<openHole>true</openHole>
		<openHole>false</openHole>
		<openHole>true</openHole>
		<openHole>true</openHole>
	</fingering>
	<fingering>
		<note>
			<name>B4</name>
			<frequency>493.88</frequency>
		</note>
		<openHole>false</openHole>
		<openHole>false</openHole>
		<openHole>true</openHole>
		<openHole>true</openHole>
		<openHole>true</openHole>
		<openHole>true</openHole>
	</fingering>  
	<fingering>
		<note>
			<name>C5</name>
			<frequency>523.25</frequency>
		</note>
		<openHole>false</openHole>
		<openHole>true</openHole>
		<openHole>false</openHole>
		<openHole>true</openHole>
		<openHole>true</openHole>
		<openHole>true</openHole>
	</fingering>
	<fingering>
		<note>
			<name>C#5</name>
			<frequency>554.37</frequency>
		</note>
		<openHole>false</openHole>
		<openHole>true</openHole>
		<openHole>true</openHole>
		<openHole>true</openHole>
		<openHole>true</openHole>
		<openHole>true</openHole>
	</fingering>  
	<fingering>
		<note>
			<name>D5</name>
			<frequency>587.33</frequency>
		</note>
		<openHole>true</openHole>
		<openHole>true</openHole>
		<openHole>false</openHole>
		<openHole>true</openHole>
		<openHole>true</openHole>
		<openHole>true</openHole>
	</fingering>
<!--	<fingering>
		<note>
			<name>D#5</name>
			<frequency>622.25</frequency>
		</note>
		<openHole>true</openHole>
		<openHole>true</openHole>
		<openHole>true</openHole>
		<openHole>true</openHole>
		<openHole>true</openHole>
		<openHole>true</openHole>
	</fingering>  -->
<!--	<fingering>
		<note>
			<name>D#5</name>
			<frequency>622.25</frequency>
		</note>
		<openHole>false</openHole>
		<openHole>true</openHole>
		<openHole>false</openHole>
		<openHole>false</openHole>
		<openHole>false</openHole>
		<openHole>false</openHole>
	</fingering>  -->
	<fingering>
		<note>
			<name>E5</name>
			<frequency>659.26</frequency>
		</note>
		<openHole>true</openHole>
		<openHole>true</openHole>
		<openHole>false</openHole>
		<openHole>false</openHole>
		<openHole>false</openHole>
		<openHole>false</openHole>
	</fingering>  
	<fingering>
		<note>
			<name>F5</name>
			<frequency>698.46</frequency>
		</note>
		<openHole>true</openHole>
		<openHole>true</openHole>
		<openHole>false</openHole>
		<openHole>false</openHole>
		<openHole>false</openHole>
		<openHole>true</openHole>
	</fingering> 
</wit:tuning>

=== Nodling/WWIDesigner/WWIDesigner/releases/1/WhistleStudy/tunings/A4-Just.xml
<?xml version="1.0" encoding="utf-8"?>
<wit:tuning xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns:wit="http://www.wwidesigner.com/Tuning"
         xsi:schemaLocation="http://www.wwidesigner.com/Tuning ../Tuning.xsd ">
	<name>Alto A JI Tuning</name>
	<comment>6-hole whistle, alto A, Just Intonation tuning.</comment>
	<numberOfHoles>6</numberOfHoles>
	<fingering>
		<note>
			<name>low A</name>
			<frequency>440.00</frequency>
		</note>
		<openHole>false</openHole><openHole>false</openHole><openHole>false</openHole>
		<openHole>false</openHole><openHole>false</openHole><openHole>false</openHole>
	</fingering>
	<fingering>
		<note>
			<name>B</name>
			<frequency>495.00</frequency>
		</note>
		<openHole>false</openHole><openHole>false</openHole><openHole>false</openHole>
		<openHole>false</openHole><openHole>false</openHole><openHole>true</openHole>
	</fingering>
	<fingering>
		<note>
			<name>C#</name>
			<frequency>550.00</frequency>
		</note>
		<openHole>false</openHole><openHole>false</openHole><openHole>false</openHole>
		<openHole>false</openHole><openHole>true</openHole><openHole>true</openHole>
	</fingering>
	<fingering>
		<note>
			<name>D</name>
			<frequency>586.67</frequency>
		</note>
		<openHole>false</openHole><openHole>false</openHole><openHole>false</openHole>
		<openHole>true</openHole><openHole>true</openHole><openHole>true</openHole>
	</fingering>
	<fingering>
		<note>
			<name>E</name>
			<frequency>660.00</frequency>
		</note>
		<openHole>false</openHole><openHole>false</openHole><openHole>true</openHole>
		<openHole>true</openHole><openHole>true</openHole><openHole>true</openHole>
	</fingering>
	<fingering>
		<note>
			<name>F#</name>
			<frequency>733.33</frequency>
		</note>
		<openHole>false</openHole><openHole>true</openHole><openHole>true</openHole>
		<openHole>true</openHole><openHole>true</openHole><openHole>true</openHole>
	</fingering>
	<fingering>
		<note>
			<name>G-nat</name>
			<frequency>782.22</frequency>
		</note>
		<openHole>true</openHole><openHole>false</openHole><openHole>false</openHole>
		<openHole>true</openHole><openHole>true</openHole><openHole>true</openHole>
	</fingering>
	<fingering>
		<note>
			<name>G#</name>
			<frequency>825.00</frequency>
		</note>
		<openHole>true</openHole><openHole>true</openHole><openHole>true</openHole>
		<openHole>true</openHole><openHole>true</openHole><openHole>true</openHole>
	</fingering>
	<fingering>
		<note>
			<name>A</name>
			<frequency>880.00</frequency>
		</note>
		<openHole>true</openHole><openHole>false</openHole><openHole>false</openHole>
		<openHole>false</openHole><openHole>false</openHole><openHole>false</openHole>
	</fingering>
	<fingering>
		<note>
			<name>B</name>
			<frequency>990.00</frequency>
		</note>
		<openHole>false</openHole><openHole>false</openHole><openHole>false</openHole>
		<openHole>false</openHole><openHole>false</openHole><openHole>true</openHole>
	</fingering>
	<fingering>
		<note>
			<name>C#</name>
			<frequency>1100.0</frequency>
		</note>
		<openHole>false</openHole><openHole>false</openHole><openHole>false</openHole>
		<openHole>false</openHole><openHole>true</openHole><openHole>true</openHole>
	</fingering>
	<fingering>
		<note>
			<name>D</name>
			<frequency>1173.3</frequency>
		</note>
		<openHole>false</openHole><openHole>false</openHole><openHole>false</openHole>
		<openHole>true</openHole><openHole>true</openHole><openHole>true</openHole>
	</fingering>
	<fingering>
		<note>
			<name>E</name>
			<frequency>1320.0</frequency>
		</note>
		<openHole>false</openHole><openHole>false</openHole><openHole>true</openHole>
		<openHole>true</openHole><openHole>true</openHole><openHole>true</openHole>
	</fingering>
	<fingering>
		<note>
			<name>F#</name>
			<frequency>1466.7</frequency>
		</note>
		<openHole>false</openHole><openHole>true</openHole><openHole>true</openHole>
		<openHole>true</openHole><openHole>true</openHole><openHole>true</openHole>
	</fingering>
	<fingering>
		<note>
			<name>G-nat</name>
			<frequency>1564.4</frequency>
		</note>
		<openHole>true</openHole><openHole>false</openHole><openHole>true</openHole>
		<openHole>false</openHole><openHole>false</openHole><openHole>false</openHole>
	</fingering>
	<fingering>
		<note>
			<name>G#</name>
			<frequency>1650.0</frequency>
		</note>
		<openHole>true</openHole><openHole>true</openHole><openHole>true</openHole>
		<openHole>true</openHole><openHole>true</openHole><openHole>true</openHole>
	</fingering>
	<fingering>
		<note>
			<name>A</name>
			<frequency>1760.0</frequency>
		</note>
		<openHole>true</openHole><openHole>false</openHole><openHole>false</openHole>
		<openHole>true</openHole><openHole>true</openHole><openHole>true</openHole>
	</fingering>

</wit:tuning>
