=== Nodling/WWIDesigner/WWIDesigner/src/main/com/wwidesigner/note/bind/Tuning.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.wwidesigner.com/Tuning" xmlns:wit="http://www.wwidesigner.com/Tuning"
	elementFormDefault="unqualified">

	<xsd:element name="temperament" type="wit:XmlTemperament">
		<xsd:annotation>
			<xsd:documentation>Persistent/reusable temperament
			</xsd:documentation>
		</xsd:annotation>
	</xsd:element>

	<xsd:element name="scaleSymbolList" type="wit:XmlScaleSymbolList">
		<xsd:annotation>
			<xsd:documentation>Persistent/reusable list of note symbols
			</xsd:documentation>
		</xsd:annotation>
	</xsd:element>

	<xsd:element name="scale" type="wit:XmlScale">
		<xsd:annotation>
			<xsd:documentation>Persistent/reusable scale</xsd:documentation>
		</xsd:annotation>
	</xsd:element>

	<xsd:element name="fingeringPattern" type="wit:XmlFingeringPattern"/>

	<xsd:element name="tuning" type="wit:XmlTuning"/>

	<xsd:complexType name="XmlScale">
		<xsd:annotation>
			<xsd:documentation>Named list of Notes</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="name" type="xsd:string"/>
			<xsd:element name="comment" type="xsd:string" maxOccurs="1" minOccurs="0"/>
			<xsd:element name="note" maxOccurs="unbounded"
				minOccurs="1">
				<xsd:complexType>
					<xsd:complexContent>
						<xsd:restriction base="wit:XmlNote">
							<xsd:sequence>
								<xsd:element name="name"
									type="xsd:string" />
								<xsd:element name="frequency"
									type="xsd:double" minOccurs="1" maxOccurs="1" />
							</xsd:sequence>
						</xsd:restriction>
					</xsd:complexContent>
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="XmlNote">
		<xsd:annotation>
			<xsd:documentation>Name/frequency pair</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="name" type="xsd:string"/>
			<xsd:element name="frequency" type="xsd:double"
				maxOccurs="1" minOccurs="0"/>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="XmlTemperament">
		<xsd:annotation>
			<xsd:documentation>Named list of intervals relative to the root
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="name" type="xsd:string"/>
			<xsd:element name="comment" type="xsd:string" maxOccurs="1" minOccurs="0"/>
			<xsd:element name="interval" type="wit:XmlOneOrMore"
				maxOccurs="unbounded" minOccurs="1" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:simpleType name="XmlOneOrMore">
		<xsd:annotation>
			<xsd:documentation>Number greater than or equal to 1.
			</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="xsd:double">
			<xsd:minInclusive value="1"/>
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:complexType name="XmlScaleSymbolList">
		<xsd:annotation>
			<xsd:documentation>Named list of note symbols</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="name" type="xsd:string"/>
			<xsd:element name="comment" type="xsd:string" maxOccurs="1" minOccurs="0"/>
			<xsd:element name="scaleSymbol" type="xsd:string"
				maxOccurs="unbounded" minOccurs="1" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="XmlFingeringPattern">
		<xsd:sequence>
			<xsd:element name="name" type="xsd:string"/>
			<xsd:element name="comment" type="xsd:string" maxOccurs="1" minOccurs="0"/>
			<xsd:element name="numberOfHoles"
				type="xsd:nonNegativeInteger" />
			<xsd:sequence>
				<xsd:element name="fingering" type="wit:XmlFingering"
					maxOccurs="unbounded" minOccurs="0" />
			</xsd:sequence>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="XmlFingering">
		<xsd:sequence>
			<xsd:element name="note" type="wit:XmlNote" maxOccurs="1"
				minOccurs="0"/>
			<xsd:sequence>
				<xsd:element name="openHole" type="xsd:boolean"
					maxOccurs="unbounded" minOccurs="0"/>
			</xsd:sequence>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="XmlTuning">
		<xsd:complexContent>
			<xsd:restriction base="wit:XmlFingeringPattern">
				<xsd:sequence>
					<xsd:element name="name" type="xsd:string"/>
					<xsd:element name="comment" type="xsd:string" maxOccurs="1" minOccurs="0"/>
					<xsd:element name="numberOfHoles"
						type="xsd:nonNegativeInteger" />
					<xsd:sequence>
						<xsd:element name="fingering"
							maxOccurs="unbounded" minOccurs="1">
							<xsd:complexType>
								<xsd:complexContent>
									<xsd:restriction
										base="wit:XmlFingering">
										<xsd:sequence>
											<xsd:element name="note"
												maxOccurs="1" minOccurs="1">
												<xsd:complexType>
													<xsd:complexContent>
														<xsd:restriction
															base="wit:XmlNote">
															<xsd:sequence>
																<xsd:element
																	name="name" type="xsd:string" />
																<xsd:element
																	name="frequency" type="xsd:double" maxOccurs="1"
																	minOccurs="1" />
															</xsd:sequence>
														</xsd:restriction>
													</xsd:complexContent>
												</xsd:complexType>
											</xsd:element>
											<xsd:sequence>
												<xsd:element
													name="openHole" type="xsd:boolean" maxOccurs="unbounded"
													minOccurs="0" />
											</xsd:sequence>
										</xsd:sequence>
									</xsd:restriction>
								</xsd:complexContent>
							</xsd:complexType>
						</xsd:element>
					</xsd:sequence>
				</xsd:sequence>
			</xsd:restriction>
		</xsd:complexContent>
	</xsd:complexType>

</xsd:schema>

=== Nodling/WWIDesigner/WWIDesigner/src/main/com/wwidesigner/note/bind/example/BP8-partial-tuning.xml
<?xml version="1.0" encoding="utf-8"?>
<wit:tuning xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns:wit="http://www.wwidesigner.com/Tuning"
         xsi:schemaLocation="http://www.wwidesigner.com/Tuning ../Tuning.xsd ">

	<name>BP8 In Progress</name>
	<comment>6-hole PVC whistle, high D, actual tuning while under construction</comment>
	<numberOfHoles>6</numberOfHoles>
	<fingering>
		<note>
			<name>low D</name>
			<frequencyMin>568</frequencyMin>
			<frequencyMax>585</frequencyMax>
		</note>
		<openHole>false</openHole><openHole>false</openHole><openHole>false</openHole>
		<openHole>false</openHole><openHole>false</openHole><openHole>false</openHole>
	</fingering>
	<fingering>
		<note>
			<name>E</name>
			<frequencyMin>630</frequencyMin>
			<frequencyMax>653</frequencyMax>
		</note>
		<openHole>false</openHole><openHole>false</openHole><openHole>false</openHole>
		<openHole>false</openHole><openHole>false</openHole><openHole>true</openHole>
	</fingering>
	<fingering>
		<note>
			<name>F#</name>
			<frequencyMin>690</frequencyMin>
			<frequencyMax>728</frequencyMax>
		</note>
		<openHole>false</openHole><openHole>false</openHole><openHole>false</openHole>
		<openHole>false</openHole><openHole>true</openHole><openHole>true</openHole>
	</fingering>
	<fingering>
		<note>
		<name>G</name>
			<frequencyMin>733</frequencyMin>
			<frequencyMax>774</frequencyMax>
		</note>
		<openHole>false</openHole><openHole>false</openHole><openHole>false</openHole>
		<openHole>true</openHole><openHole>true</openHole><openHole>true</openHole>
	</fingering>
	<fingering>
		<note>
		<name>A</name>
			<frequencyMin>825</frequencyMin>
			<frequencyMax>878</frequencyMax>
		</note>
		<openHole>false</openHole><openHole>false</openHole><openHole>true</openHole>
		<openHole>true</openHole><openHole>true</openHole><openHole>true</openHole>
	</fingering>
	<fingering>
		<note>
		<name>B</name>
			<frequencyMin>895</frequencyMin>
			<frequencyMax>978</frequencyMax>
		</note>
		<openHole>false</openHole><openHole>true</openHole><openHole>true</openHole>
		<openHole>true</openHole><openHole>true</openHole><openHole>true</openHole>
	</fingering>
	<fingering>
		<note>
		<name>C-nat</name>
			<frequencyMin>939</frequencyMin>
			<frequencyMax>1027</frequencyMax>
		</note>
		<openHole>true</openHole><openHole>false</openHole><openHole>false</openHole>
		<openHole>true</openHole><openHole>true</openHole><openHole>true</openHole>
	</fingering>
	<fingering>
		<note>
			<name>C#</name>
			<frequencyMin>1000</frequencyMin>
			<frequencyMax>1092</frequencyMax>
		</note>
		<openHole>true</openHole><openHole>true</openHole><openHole>true</openHole>
		<openHole>true</openHole><openHole>true</openHole><openHole>true</openHole>
	</fingering>
	<fingering>
		<note>
			<name>D</name>
			<frequencyMin>1116</frequencyMin>
			<frequencyMax>1191</frequencyMax>
		</note>
		<openHole>true</openHole><openHole>false</openHole><openHole>false</openHole>
		<openHole>false</openHole><openHole>false</openHole><openHole>false</openHole>
	</fingering>
	<fingering>
		<note>
			<name>E</name>
			<frequencyMin>1238</frequencyMin>
			<frequencyMax>1315</frequencyMax>
		</note>
		<openHole>false</openHole><openHole>false</openHole><openHole>false</openHole>
		<openHole>false</openHole><openHole>false</openHole><openHole>true</openHole>
	</fingering>
	<fingering>
		<note>
			<name>F#</name>
			<frequencyMin>1366</frequencyMin>
			<frequencyMax>1460</frequencyMax>
		</note>
		<openHole>false</openHole><openHole>false</openHole><openHole>false</openHole>
		<openHole>false</openHole><openHole>true</openHole><openHole>true</openHole>
	</fingering>
	<fingering>
		<note>
		<name>G</name>
			<frequencyMin>1456</frequencyMin>
			<frequencyMax>1560</frequencyMax>
		</note>
		<openHole>false</openHole><openHole>false</openHole><openHole>false</openHole>
		<openHole>true</openHole><openHole>true</openHole><openHole>true</openHole>
	</fingering>
	<fingering>
		<note>
			<name>A</name>
			<frequencyMin>1648</frequencyMin>
			<frequencyMax>1761</frequencyMax>
		</note>
		<openHole>false</openHole><openHole>false</openHole><openHole>true</openHole>
		<openHole>true</openHole><openHole>true</openHole><openHole>true</openHole>
	</fingering>
	<fingering>
		<note>
		<name>B</name>
			<frequencyMin>1830</frequencyMin>
			<frequencyMax>1940</frequencyMax>
		</note>
		<openHole>false</openHole><openHole>true</openHole><openHole>true</openHole>
		<openHole>true</openHole><openHole>true</openHole><openHole>true</openHole>
	</fingering>
	<fingering>
		<note>
			<name>high C-nat</name>
			<frequencyMin>1901</frequencyMin>
			<frequencyMax>1937</frequencyMax>
		</note>
		<openHole>true</openHole><openHole>false</openHole><openHole>true</openHole>
		<openHole>true</openHole><openHole>true</openHole><openHole>true</openHole>
	</fingering>
	<fingering>
		<note>
			<name>C#</name>
			<frequencyMin>2031</frequencyMin>
			<frequencyMax>2112</frequencyMax>
		</note>
		<openHole>true</openHole><openHole>true</openHole><openHole>true</openHole>
		<openHole>true</openHole><openHole>true</openHole><openHole>true</openHole>
	</fingering>
	<fingering>
		<note>
			<name>high D</name>
			<frequencyMin>2332</frequencyMin>
			<frequencyMax>2408</frequencyMax>
		</note>
		<openHole>true</openHole><openHole>false</openHole><openHole>false</openHole>
		<openHole>false</openHole><openHole>false</openHole><openHole>false</openHole>
	</fingering>
	<fingering>
		<note>
			<name>pre-D</name>
			<frequencyMin>840</frequencyMin>
			<frequencyMax>857</frequencyMax>
		</note>
		<openHole>true</openHole><openHole>false</openHole><openHole>false</openHole>
		<openHole>false</openHole><openHole>false</openHole><openHole>false</openHole>
	</fingering>

</wit:tuning>

=== Nodling/WWIDesigner/WWIDesigner/src/test/com/wwidesigner/optimization/example/NoHoleNAF1Tuning.xml
<?xml version="1.0" encoding="UTF-8"?>
<wit:tuning xmlns:wit="http://www.wwidesigner.com/Tuning" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.wwidesigner.com/Tuning ../../../../../main/com/wwidesigner/note/bind/Tuning.xsd ">
  <name>No hole NAF1 tuning</name>
  <comment>Tuning for NoHoleNAF1.xml</comment>
  <numberOfHoles>0</numberOfHoles>
  <fingering>
    <note>
      <name>A</name>
      <frequency>441.27</frequency>
    </note>
  </fingering>
</wit:tuning>

=== Nodling/WWIDesigner/WWIDesigner/src/test/com/wwidesigner/optimization/example/6HoleNAF1Tuning.xml
<?xml version="1.0" encoding="UTF-8"?>
<wit:tuning xmlns:wit="http://www.wwidesigner.com/Tuning"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.wwidesigner.com/Tuning ../../../../../main/com/wwidesigner/note/bind/Tuning.xsd ">
	<name>6 hole NAF1 tuning</name>
	<comment>Tuning for 6HoleNAF1.xml</comment>
	<numberOfHoles>6</numberOfHoles>
	<fingering>
		<note>
			<name>A4</name>
			<frequency>440</frequency>
		</note>
		<openHole>false</openHole>
		<openHole>false</openHole>
		<openHole>false</openHole>
		<openHole>false</openHole>
		<openHole>false</openHole>
		<openHole>false</openHole>
	</fingering>
	<fingering>
		<note>
			<name>C5</name>
			<frequency>523.25</frequency>
		</note>
		<openHole>false</openHole>
		<openHole>false</openHole>
		<openHole>false</openHole>
		<openHole>false</openHole>
		<openHole>false</openHole>
		<openHole>true</openHole>
	</fingering>
	<fingering>
		<note>
			<name>C#5</name>
			<frequency>554.37</frequency>
		</note>
		<openHole>false</openHole>
		<openHole>false</openHole>
		<openHole>false</openHole>
		<openHole>false</openHole>
		<openHole>true</openHole>
		<openHole>false</openHole>
	</fingering>
	<fingering>
		<note>
			<name>D5</name>
			<frequency>587.33</frequency>
		</note>
		<openHole>false</openHole>
		<openHole>false</openHole>
		<openHole>false</openHole>
		<openHole>false</openHole>
		<openHole>true</openHole>
		<openHole>true</openHole>
	</fingering>
	<fingering>
		<note>
			<name>D#5</name>
			<frequency>622.25</frequency>
		</note>
		<openHole>false</openHole>
		<openHole>false</openHole>
		<openHole>false</openHole>
		<openHole>true</openHole>
		<openHole>false</openHole>
		<openHole>true</openHole>
	</fingering>
	<fingering>
		<note>
			<name>E5</name>
			<frequency>659.26</frequency>
		</note>
		<openHole>false</openHole>
		<openHole>false</openHole>
		<openHole>false</openHole>
		<openHole>true</openHole>
		<openHole>true</openHole>
		<openHole>true</openHole>
	</fingering>
	<fingering>
		<note>
			<name>F5</name>
			<frequency>698.46</frequency>
		</note>
		<openHole>false</openHole>
		<openHole>false</openHole>
		<openHole>true</openHole>
		<openHole>false</openHole>
		<openHole>true</openHole>
		<openHole>true</openHole>
	</fingering>
	<fingering>
		<note>
			<name>F#5</name>
			<frequency>739.99</frequency>
		</note>
		<openHole>false</openHole>
		<openHole>false</openHole>
		<openHole>true</openHole>
		<openHole>true</openHole>
		<openHole>true</openHole>
		<openHole>true</openHole>
	</fingering>
	<fingering>
		<note>
			<name>G5</name>
			<frequency>783.99</frequency>
		</note>
		<openHole>false</openHole>
		<openHole>true</openHole>
		<openHole>false</openHole>
		<openHole>true</openHole>
		<openHole>true</openHole>
		<openHole>true</openHole>
	</fingering>
	<fingering>
		<note>
			<name>G#5</name>
			<frequency>830.61</frequency>
		</note>
		<openHole>false</openHole>
		<openHole>true</openHole>
		<openHole>true</openHole>
		<openHole>true</openHole>
		<openHole>true</openHole>
		<openHole>true</openHole>
	</fingering>
	<fingering>
		<note>
			<name>A5</name>
			<frequency>880</frequency>
		</note>
		<openHole>true</openHole>
		<openHole>true</openHole>
		<openHole>false</openHole>
		<openHole>true</openHole>
		<openHole>true</openHole>
		<openHole>true</openHole>
	</fingering>
<!-- 	<fingering>
		<note>
			<name>A#5</name>
			<frequency>932.33</frequency>
		</note>
		<openHole>false</openHole>
		<openHole>true</openHole>
		<openHole>false</openHole>
		<openHole>false</openHole>
		<openHole>false</openHole>
		<openHole>false</openHole>
	</fingering> -->
	<fingering>
		<note>
			<name>B5</name>
			<frequency>987.77</frequency>
		</note>
		<openHole>true</openHole>
		<openHole>true</openHole>
		<openHole>false</openHole>
		<openHole>false</openHole>
		<openHole>false</openHole>
		<openHole>false</openHole>
	</fingering>
	<fingering>
		<note>
			<name>C6</name>
			<frequency>1046.5</frequency>
		</note>
		<openHole>true</openHole>
		<openHole>true</openHole>
		<openHole>false</openHole>
		<openHole>false</openHole>
		<openHole>false</openHole>
		<openHole>true</openHole>
	</fingering>
</wit:tuning>

=== Nodling/WWIDesigner/WWIDesigner/src/test/com/wwidesigner/optimization/example/LightG6HoleNAFTuning.xml
<?xml version="1.0" encoding="UTF-8"?>
<wit:tuning xmlns:wit="http://www.wwidesigner.com/Tuning"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.wwidesigner.com/Tuning ../../../../../main/com/wwidesigner/note/bind/Tuning.xsd ">
	<name>Ken Light G, 6 hole NAF tuning</name>
	<comment>Tuning for Ken Light PVC G, standard fingering. Tuning done at 74.0 F.</comment>
	<numberOfHoles>6</numberOfHoles>
	<fingering>
		<note>
			<name>G4</name>
			<frequency>393.13</frequency>
			<frequencyMin>372.14</frequencyMin>
			<frequencyMax>396.55</frequencyMax>
		</note>
		<openHole>false</openHole>
		<openHole>false</openHole>
		<openHole>false</openHole>
		<openHole>false</openHole>
		<openHole>false</openHole>
		<openHole>false</openHole>
	</fingering>
	<fingering>
		<note>
			<name>A#4</name>
			<frequency>466.7</frequency>
			<frequencyMin>442.55</frequencyMin>
			<frequencyMax>482.6</frequencyMax>
		</note>
		<openHole>false</openHole>
		<openHole>false</openHole>
		<openHole>false</openHole>
		<openHole>false</openHole>
		<openHole>false</openHole>
		<openHole>true</openHole>
	</fingering>
	<fingering>
		<note>
			<name>B4</name>
			<frequency>495.31</frequency>
			<frequencyMin>466.16</frequencyMin>
			<frequencyMax>517.24</frequencyMax>
		</note>
		<openHole>false</openHole>
		<openHole>false</openHole>
		<openHole>false</openHole>
		<openHole>false</openHole>
		<openHole>true</openHole>
		<openHole>false</openHole>
	</fingering>
	<fingering>
		<note>
			<name>C5</name>
			<frequency>520.24</frequency>
			<frequencyMin>491.04</frequencyMin>
			<frequencyMax>548</frequencyMax>
		</note>
		<openHole>false</openHole>
		<openHole>false</openHole>
		<openHole>false</openHole>
		<openHole>false</openHole>
		<openHole>true</openHole>
		<openHole>true</openHole>
	</fingering>
	<fingering>
		<note>
			<name>C#5</name>
			<frequency>558.22</frequency>
			<frequencyMin>523.25</frequencyMin>
			<frequencyMax>587.33</frequencyMax>
		</note>
		<openHole>false</openHole>
		<openHole>false</openHole>
		<openHole>false</openHole>
		<openHole>true</openHole>
		<openHole>false</openHole>
		<openHole>true</openHole>
	</fingering>
	<fingering>
		<note>
			<name>D5</name>
			<frequency>580.58</frequency>
			<frequencyMin>535.48</frequencyMin>
			<frequencyMax>611.56</frequencyMax>
		</note>
		<openHole>false</openHole>
		<openHole>false</openHole>
		<openHole>false</openHole>
		<openHole>true</openHole>
		<openHole>true</openHole>
		<openHole>true</openHole>
	</fingering>
	<fingering>
		<note>
			<name>D#5</name>
			<frequency>626.58</frequency>
			<frequencyMin>580.58</frequencyMin>
			<frequencyMax>663.07</frequencyMax>
		</note>
		<openHole>false</openHole>
		<openHole>false</openHole>
		<openHole>true</openHole>
		<openHole>false</openHole>
		<openHole>true</openHole>
		<openHole>true</openHole>
	</fingering>
	<fingering>
		<note>
			<name>E5</name>
			<frequency>649.8</frequency>
			<frequencyMin>618.67</frequencyMin>
			<frequencyMax>696.44</frequencyMax>
		</note>
		<openHole>false</openHole>
		<openHole>false</openHole>
		<openHole>true</openHole>
		<openHole>true</openHole>
		<openHole>true</openHole>
		<openHole>true</openHole>
	</fingering>
	<fingering>
		<note>
			<name>F5</name>
			<frequency>702.5</frequency>
			<frequencyMin>647.93</frequencyMin>
			<frequencyMax>763.88</frequencyMax>
		</note>
		<openHole>false</openHole>
		<openHole>true</openHole>
		<openHole>false</openHole>
		<openHole>true</openHole>
		<openHole>true</openHole>
		<openHole>true</openHole>
	</fingering>
	<fingering>
		<note>
			<name>F#5</name>
			<frequency>742.13</frequency>
			<frequencyMin>655.46</frequencyMin>
			<frequencyMax>825.83</frequencyMax>
		</note>
		<openHole>false</openHole>
		<openHole>true</openHole>
		<openHole>true</openHole>
		<openHole>true</openHole>
		<openHole>true</openHole>
		<openHole>true</openHole>
	</fingering>
	<fingering>
		<note>
			<name>G5</name>
			<frequency>825.83</frequency>
			<frequencyMin>727.28</frequencyMin>
			<frequencyMax>911.03</frequencyMax>
		</note>
		<openHole>true</openHole>
		<openHole>true</openHole>
		<openHole>false</openHole>
		<openHole>true</openHole>
		<openHole>true</openHole>
		<openHole>true</openHole>
	</fingering>
	<fingering>
		<note>
			<name>G#5</name>
			<frequency>845.13</frequency>
			<frequencyMin>770.52</frequencyMin>
			<frequencyMax>976.42</frequencyMax>
		</note>
		<openHole>true</openHole>
		<openHole>true</openHole>
		<openHole>true</openHole>
		<openHole>true</openHole>
		<openHole>true</openHole>
		<openHole>true</openHole>
	</fingering>
	<fingering>
		<note>
			<name>A5</name>
			<frequency>880.00</frequency>
			<frequencyMin>752.92</frequencyMin>
			<frequencyMax>954.12</frequencyMax>
		</note>
		<openHole>true</openHole>
		<openHole>true</openHole>
		<openHole>false</openHole>
		<openHole>false</openHole>
		<openHole>false</openHole>
		<openHole>false</openHole>
	</fingering>
	<fingering>
		<note>
			<name>A#5</name>
			<frequency>929.64</frequency>
			<frequencyMin>890.23</frequencyMin>
			<frequencyMax>1005.03</frequencyMax>
		</note>
		<openHole>true</openHole>
		<openHole>true</openHole>
		<openHole>false</openHole>
		<openHole>false</openHole>
		<openHole>false</openHole>
		<openHole>true</openHole>
	</fingering>
</wit:tuning>

=== Nodling/WWIDesigner/WWIDesigner/src/test/com/wwidesigner/optimization/example/1HoleNAF1Tuning.xml
<?xml version="1.0" encoding="UTF-8"?>
<wit:tuning xmlns:wit="http://www.wwidesigner.com/Tuning"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.wwidesigner.com/Tuning ../../../../../main/com/wwidesigner/note/bind/Tuning.xsd ">
	<name>1 hole NAF1 tuning</name>
	<comment>Tuning for 1HoleNAF1.xml</comment>
	<numberOfHoles>1</numberOfHoles>
	<fingering>
		<note>
			<name>A4</name>
			<frequency>440</frequency>
		</note>
		<openHole>false</openHole>
	</fingering>
	<fingering>
		<note>
			<name>C5</name>
			<frequency>523.25</frequency>
		</note>
		<openHole>true</openHole>
	</fingering>
</wit:tuning>

=== Nodling/WWIDesigner/WWIDesigner/src/test/com/wwidesigner/optimization/example/BP8-partial-tuning.xml
<?xml version="1.0" encoding="utf-8"?>
<wit:tuning xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns:wit="http://www.wwidesigner.com/Tuning"
         xsi:schemaLocation="http://www.wwidesigner.com/Tuning ../Tuning.xsd ">

	<name>BP8 In Progress</name>
	<comment>6-hole PVC whistle, high D, actual tuning while under construction</comment>
	<numberOfHoles>6</numberOfHoles>
	<fingering>
		<note>
			<name>low D</name>
			<frequency>587</frequency>
			<frequencyMin>568</frequencyMin>
			<frequencyMax>585</frequencyMax>
		</note>
		<openHole>false</openHole><openHole>false</openHole><openHole>false</openHole>
		<openHole>false</openHole><openHole>false</openHole><openHole>false</openHole>
	</fingering>
	<fingering>
		<note>
			<name>E</name>
			<frequency>652</frequency>
			<frequencyMin>630</frequencyMin>
			<frequencyMax>653</frequencyMax>
		</note>
		<openHole>false</openHole><openHole>false</openHole><openHole>false</openHole>
		<openHole>false</openHole><openHole>false</openHole><openHole>true</openHole>
	</fingering>
	<fingering>
		<note>
			<name>F#</name>
			<frequency>719</frequency>
			<frequencyMin>690</frequencyMin>
			<frequencyMax>728</frequencyMax>
		</note>
		<openHole>false</openHole><openHole>false</openHole><openHole>false</openHole>
		<openHole>false</openHole><openHole>true</openHole><openHole>true</openHole>
	</fingering>
	<fingering>
		<note>
		<name>G</name>
			<frequency>764</frequency>
			<frequencyMin>733</frequencyMin>
			<frequencyMax>774</frequencyMax>
		</note>
		<openHole>false</openHole><openHole>false</openHole><openHole>false</openHole>
		<openHole>true</openHole><openHole>true</openHole><openHole>true</openHole>
	</fingering>
	<fingering>
		<note>
		<name>A</name>
			<frequency>861</frequency>
			<frequencyMin>825</frequencyMin>
			<frequencyMax>878</frequencyMax>
		</note>
		<openHole>false</openHole><openHole>false</openHole><openHole>true</openHole>
		<openHole>true</openHole><openHole>true</openHole><openHole>true</openHole>
	</fingering>
	<fingering>
		<note>
		<name>B</name>
			<frequency>954</frequency>
			<frequencyMin>895</frequencyMin>
			<frequencyMax>978</frequencyMax>
		</note>
		<openHole>false</openHole><openHole>true</openHole><openHole>true</openHole>
		<openHole>true</openHole><openHole>true</openHole><openHole>true</openHole>
	</fingering>
	<fingering>
		<note>
		<name>C-nat</name>
			<frequency>999</frequency>
			<frequencyMin>939</frequencyMin>
			<frequencyMax>1027</frequencyMax>
		</note>
		<openHole>true</openHole><openHole>false</openHole><openHole>false</openHole>
		<openHole>true</openHole><openHole>true</openHole><openHole>true</openHole>
	</fingering>
	<fingering>
		<note>
			<name>C#</name>
			<frequency>1060</frequency>
			<frequencyMin>1000</frequencyMin>
			<frequencyMax>1092</frequencyMax>
		</note>
		<openHole>true</openHole><openHole>true</openHole><openHole>true</openHole>
		<openHole>true</openHole><openHole>true</openHole><openHole>true</openHole>
	</fingering>
	<fingering>
		<note>
			<name>D</name>
			<frequency>1162</frequency>
			<frequencyMin>1116</frequencyMin>
			<frequencyMax>1191</frequencyMax>
		</note>
		<openHole>true</openHole><openHole>false</openHole><openHole>false</openHole>
		<openHole>false</openHole><openHole>false</openHole><openHole>false</openHole>
	</fingering>
	<fingering>
		<note>
			<name>E</name>
			<frequency>1295</frequency>
			<frequencyMin>1238</frequencyMin>
			<frequencyMax>1315</frequencyMax>
		</note>
		<openHole>false</openHole><openHole>false</openHole><openHole>false</openHole>
		<openHole>false</openHole><openHole>false</openHole><openHole>true</openHole>
	</fingering>
	<fingering>
		<note>
			<name>F#</name>
			<frequency>1420</frequency>
			<frequencyMin>1366</frequencyMin>
			<frequencyMax>1460</frequencyMax>
		</note>
		<openHole>false</openHole><openHole>false</openHole><openHole>false</openHole>
		<openHole>false</openHole><openHole>true</openHole><openHole>true</openHole>
	</fingering>
	<fingering>
		<note>
		<name>G</name>
			<frequency>1510</frequency>
			<frequencyMin>1456</frequencyMin>
			<frequencyMax>1560</frequencyMax>
		</note>
		<openHole>false</openHole><openHole>false</openHole><openHole>false</openHole>
		<openHole>true</openHole><openHole>true</openHole><openHole>true</openHole>
	</fingering>
	<fingering>
		<note>
			<name>A</name>
			<frequency>1689</frequency>
			<frequencyMin>1648</frequencyMin>
			<frequencyMax>1761</frequencyMax>
		</note>
		<openHole>false</openHole><openHole>false</openHole><openHole>true</openHole>
		<openHole>true</openHole><openHole>true</openHole><openHole>true</openHole>
	</fingering>
	<fingering>
		<note>
		<name>B</name>
			<frequency>1863</frequency>
			<frequencyMin>1830</frequencyMin>
			<frequencyMax>1940</frequencyMax>
		</note>
		<openHole>false</openHole><openHole>true</openHole><openHole>true</openHole>
		<openHole>true</openHole><openHole>true</openHole><openHole>true</openHole>
	</fingering>
	<fingering>
		<note>
			<name>hi C-nat</name>
			<frequency>1903</frequency>
			<frequencyMin>1901</frequencyMin>
			<frequencyMax>1937</frequencyMax>
		</note>
		<openHole>true</openHole><openHole>false</openHole><openHole>true</openHole>
		<openHole>true</openHole><openHole>true</openHole><openHole>true</openHole>
	</fingering>
	<fingering>
		<note>
			<name>C#</name>
			<frequency>2063</frequency>
			<frequencyMin>2031</frequencyMin>
			<frequencyMax>2112</frequencyMax>
		</note>
		<openHole>true</openHole><openHole>true</openHole><openHole>true</openHole>
		<openHole>true</openHole><openHole>true</openHole><openHole>true</openHole>
	</fingering>
	<fingering>
		<note>
			<name>high D</name>
			<frequency>2345</frequency>
			<frequencyMin>2332</frequencyMin>
			<frequencyMax>2408</frequencyMax>
		</note>
		<openHole>true</openHole><openHole>false</openHole><openHole>false</openHole>
		<openHole>false</openHole><openHole>false</openHole><openHole>false</openHole>
	</fingering>
	<fingering>
		<note>
			<name>pre-D</name>
			<frequencyMin>840</frequencyMin>
			<frequencyMax>857</frequencyMax>
		</note>
		<openHole>true</openHole><openHole>false</openHole><openHole>false</openHole>
		<openHole>false</openHole><openHole>false</openHole><openHole>false</openHole>
	</fingering>

</wit:tuning>
